{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_USER: {{ .Values.postgresql.credentials.user }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.credentials.password }}
  POSTGRES_DB: {{ .Values.postgresql.credentials.db }}
{{- end }}
